Repository raduschirliu/cpsc585, pull requests merged in 2023-04, with the labels that each got.

#127 feat: add shadows
  game/resources/assets.jsonc
  game/resources/models/track3/track3-10.bin
  game/resources/models/track3/track3-10.gltf
  game/resources/shaders/blinnphong.frag
  game/resources/shaders/debug.frag
  game/resources/shaders/debug.vert
  game/resources/shaders/depth_map.frag
  game/resources/shaders/depth_map.vert
  game/resources/shaders/lit.frag
  game/resources/shaders/lit.vert
  game/resources/shaders/skybox.frag
  game/resources/shaders/skybox.vert
  game/src/engine/App.cpp
  game/src/engine/asset/AssetService.cpp
  game/src/engine/core/gfx/GLHandles.cpp
  game/src/engine/core/gfx/GLHandles.h
  game/src/engine/core/gfx/ShaderProgram.cpp
  game/src/engine/core/gfx/Texture.cpp
  game/src/engine/core/gfx/Texture.h
  game/src/engine/core/gfx/Window.cpp
  game/src/engine/core/gfx/Window.h
  game/src/engine/core/gui/PropertyWidgets.cpp
  game/src/engine/core/gui/PropertyWidgets.h
  game/src/engine/core/math/Cuboid.cpp
  game/src/engine/core/math/Cuboid.h
  game/src/engine/core/math/Rect2d.cpp
  game/src/engine/core/math/Rect2d.h
  game/src/engine/fwd/FwdComponents.h
  game/src/engine/gui/GuiService.cpp
  game/src/engine/physics/PhysicsService.cpp
  game/src/engine/render/Camera.cpp
  game/src/engine/render/Camera.h
  game/src/engine/render/DebugDrawList.cpp
  game/src/engine/render/DebugDrawList.h
  game/src/engine/render/RenderBuffers.h
  game/src/engine/render/RenderService.cpp
  game/src/engine/render/RenderService.h
  game/src/engine/render/SceneRenderData.cpp
  game/src/engine/render/SceneRenderData.h
  game/src/engine/render/passes/DepthPass.cpp
  game/src/engine/render/passes/DepthPass.h
  game/src/engine/render/passes/GeometryPass.cpp
  game/src/engine/render/passes/GeometryPass.h
  game/src/engine/render/passes/depth/ShadowMap.cpp
  game/src/engine/render/passes/depth/ShadowMap.h
  game/src/engine/service/Service.cpp
  game/src/engine/service/Service.h
  game/src/engine/service/ServiceProvider.cpp
  game/src/engine/service/ServiceProvider.h
  game/src/game/GameApp.cpp
  game/src/game/components/Controllers/AIController.cpp
  game/src/game/components/DebugCameraController.cpp
  game/src/game/components/DebugCameraController.h
  game/src/game/services/GameStateService.cpp
Labels: feature, renderer, framework

#166 feat: respawn on death + minor fix to ammo pickups
  game/src/game/GameApp.cpp
  game/src/game/components/Controllers/AIController.cpp
  game/src/game/components/Controllers/PlayerController.cpp
  game/src/game/components/Controllers/PlayerController.h
  game/src/game/components/Pickups/AmmoType/BuckshotPickup.cpp
  game/src/game/components/Pickups/AmmoType/DoubleDamagePickup.cpp
  game/src/game/components/Pickups/AmmoType/ExploadingBulletPickup.cpp
  game/src/game/components/Pickups/AmmoType/IncreaseFireRatePickup.cpp
  game/src/game/components/VehicleComponent.cpp
  game/src/game/components/VehicleComponent.h
  game/src/game/components/state/PlayerState.cpp
  game/src/game/components/state/PlayerState.h
  game/src/game/services/GameStateService.cpp
Labels: feature, gameplay

#178 feat: make the laser something other than a 1px line
  assets/shaders/laser.sprj
  assets/shaders/laser_mask.png
  assets/shaders/shaders/DefaultPS.glsl
  assets/shaders/shaders/DefaultVS.glsl
  assets/shaders/shaders/laser_SimplePS.glsl
  assets/shaders/shaders/laser_SimpleVS.glsl
  game/resources/assets.jsonc
  game/resources/checkpoints/checkpoints.obj
  game/resources/shaders/laser.frag
  game/resources/shaders/laser.vert
  game/resources/shaders/lit.frag
  game/resources/textures/blank.jpg
  game/resources/textures/particle/laser_mask.png
  game/src/engine/core/math/Quad.h
  game/src/engine/physics/PhysicsService.cpp
  game/src/engine/physics/PhysicsService.h
  game/src/engine/render/LaserMaterial.cpp
  game/src/engine/render/LaserMaterial.h
  game/src/engine/render/Material.h
  game/src/engine/render/MeshRenderer.cpp
  game/src/engine/render/MeshRenderer.h
  game/src/engine/render/RenderService.cpp
  game/src/engine/render/RenderService.h
  game/src/engine/render/SceneRenderData.cpp
  game/src/engine/render/SceneRenderData.h
  game/src/engine/render/passes/GeometryPass.cpp
  game/src/engine/render/passes/GeometryPass.h
  game/src/game/components/shooting/Shooter.cpp
  game/src/game/components/shooting/Shooter.h
Labels: feature, renderer

#180 feat: simple postprocessing, gamma correction, HDR
  game/resources/shaders/post_process.frag
  game/resources/shaders/post_process.vert
  game/src/engine/core/gfx/GLHandles.cpp
  game/src/engine/core/gfx/GLHandles.h
  game/src/engine/core/gfx/Texture.cpp
  game/src/engine/core/gfx/Texture.h
  game/src/engine/core/gfx/Window.cpp
  game/src/engine/render/RenderService.cpp
  game/src/engine/render/RenderService.h
  game/src/engine/render/passes/GeometryPass.cpp
  game/src/engine/render/passes/GeometryPass.h
  game/src/engine/render/passes/PostProcessPass.cpp
  game/src/engine/render/passes/PostProcessPass.h
  game/src/engine/render/passes/depth/ShadowMap.cpp
Labels: renderer, framework
