Repository raduschirliu/cpsc585, pull requests merged in 2023-02, with the labels that each got.

#26 fix: various compilation errors, shader issues
  game/resources/shaders/basic.frag
  game/resources/shaders/default.vert
  game/src/engine/asset/AssetService.cpp
  game/src/engine/config/VehicleData.h
  game/src/engine/core/debug/Assert.h
  game/src/engine/core/gfx/GLDebug.cpp
  game/src/engine/core/gfx/GLDebug.h
  game/src/engine/core/gfx/ShaderProgram.cpp
  game/src/engine/core/gfx/Window.cpp
  game/src/engine/render/RenderService.cpp
  game/src/game/GameApp.cpp
Labels: bug

#27 chore: each scene holds its own event bus
  game/src/engine/App.cpp
  game/src/engine/App.h
  game/src/engine/config/VehicleData.h
  game/src/engine/gui/GuiService.cpp
  game/src/engine/scene/Scene.cpp
  game/src/engine/scene/Scene.h
  game/src/engine/scene/SceneList.cpp
  game/src/engine/scene/SceneList.h
  game/src/engine/service/Service.cpp
  game/src/engine/service/Service.h
  game/src/engine/service/ServiceProvider.cpp
  game/src/engine/service/ServiceProvider.h
  game/src/game/GameApp.cpp
Labels: bug, framework

#29 fix: introduce timestep for OnUpdate event
  game/src/engine/core/event/EventBus.h
  game/src/engine/core/event/EventDispatcher.h
  game/src/engine/core/event/EventHandler.h
  game/src/engine/core/math/Timestep.cpp
  game/src/engine/core/math/Timestep.h
  game/src/engine/gui/OnGuiEvent.h
  game/src/engine/physics/CubeRigidbody.cpp
  game/src/engine/physics/CubeRigidbody.h
  game/src/engine/physics/SphereRigidbody.cpp
  game/src/engine/physics/SphereRigidbody.h
  game/src/engine/render/Camera.cpp
  game/src/engine/render/Camera.h
  game/src/engine/scene/ComponentUpdateService.cpp
  game/src/engine/scene/ComponentUpdateService.h
  game/src/engine/scene/OnUpdateEvent.h
  game/src/engine/scene/Transform.cpp
  game/src/engine/scene/Transform.h
  game/src/game/components/BasicComponent.cpp
  game/src/game/components/BasicComponent.h
  game/src/game/components/DebugCameraController.cpp
  game/src/game/components/DebugCameraController.h
  game/src/game/components/GuiExampleComponent.cpp
  game/src/game/components/GuiExampleComponent.h
Labels: bug, framework

#38 Scene entity/component debugging tools
  game/src/engine/App.cpp
  game/src/engine/App.h
  game/src/engine/core/event/EventBus.h
  game/src/engine/render/MeshRenderer.cpp
  game/src/engine/render/MeshRenderer.h
  game/src/engine/scene/Component.cpp
  game/src/engine/scene/Component.h
  game/src/engine/scene/Entity.cpp
  game/src/engine/scene/Entity.h
  game/src/engine/scene/Scene.cpp
  game/src/engine/scene/Scene.h
  game/src/engine/scene/SceneDebugService.cpp
  game/src/engine/scene/SceneDebugService.h
  game/src/engine/scene/Transform.cpp
  game/src/engine/scene/Transform.h
  game/src/engine/service/Service.cpp
  game/src/engine/service/Service.h
  game/src/engine/service/ServiceProvider.cpp
  game/src/engine/service/ServiceProvider.h
  game/src/game/GameApp.cpp
  game/src/game/components/VehicleComponent.cpp
Labels: feature, framework

#43 feat: add lighting
  game/resources/shaders/blinnphong.frag
  game/src/engine/core/gfx/ShaderProgram.cpp
  game/src/engine/core/gfx/ShaderProgram.h
  game/src/engine/core/gui/PropertyWidgets.cpp
  game/src/engine/core/gui/PropertyWidgets.h
  game/src/engine/render/Camera.cpp
  game/src/engine/render/Camera.h
  game/src/engine/render/Material.cpp
  game/src/engine/render/Material.h
  game/src/engine/render/MeshRenderer.cpp
  game/src/engine/render/MeshRenderer.h
  game/src/engine/render/PointLight.cpp
  game/src/engine/render/PointLight.h
  game/src/engine/render/RenderService.cpp
  game/src/engine/render/RenderService.h
  game/src/engine/render/Renderable.h
  game/src/engine/scene/SceneDebugService.cpp
  game/src/engine/scene/Transform.cpp
  game/src/game/GameApp.cpp
  game/src/game/components/VehicleComponent.cpp
Labels: renderer, framework

#39 Feat: raycasting
  game/src/engine/physics/PhysicsService.cpp
  game/src/engine/physics/PhysicsService.h
  game/src/engine/physics/RaycastData.cpp
  game/src/engine/physics/RaycastData.h
  game/src/game/GameApp.cpp
  game/src/game/components/GuiExampleComponent.cpp
  game/src/game/components/RaycastComponent.cpp
  game/src/game/components/RaycastComponent.h
Labels: physics

#46 feat: add collision triggers
  game/src/engine/physics/BoxTrigger.cpp
  game/src/engine/physics/BoxTrigger.h
  game/src/engine/physics/PhysicsService.cpp
  game/src/engine/physics/PhysicsService.h
  game/src/engine/physics/PlaneStaticBody.cpp
  game/src/engine/scene/Component.cpp
  game/src/engine/scene/Component.h
  game/src/engine/scene/EventData.h
  game/src/game/GameApp.cpp
  game/src/game/components/FinishLineComponent.cpp
  game/src/game/components/FinishLineComponent.h
Labels: feature, framework, physics

#78 Add hot reloading
  docs/Keybinds.md
  game/resources/vehicle_data/Base.jsonc
  game/resources/vehicle_data/DirectDrive.jsonc
  game/resources/vehicle_data/EngineDrive.jsonc
  game/src/engine/App.cpp
  game/src/engine/App.h
  game/src/engine/core/debug/Assert.h
  game/src/engine/core/event/EventBus.h
  game/src/engine/physics/PhysicsService.cpp
  game/src/engine/physics/PhysicsService.h
  game/src/engine/physics/PlaneStaticBody.cpp
  game/src/engine/physics/PlaneStaticBody.h
  game/src/engine/physics/RigidBodyComponent.cpp
  game/src/engine/physics/RigidBodyComponent.h
  game/src/engine/render/Camera.cpp
  game/src/engine/render/Camera.h
  game/src/engine/render/MeshRenderer.cpp
  game/src/engine/render/MeshRenderer.h
  game/src/engine/render/PointLight.cpp
  game/src/engine/render/PointLight.h
  game/src/engine/render/RenderService.cpp
  game/src/engine/render/RenderService.h
  game/src/engine/scene/Component.cpp
  game/src/engine/scene/Component.h
  game/src/engine/scene/Entity.cpp
  game/src/engine/scene/Entity.h
  game/src/engine/scene/Scene.cpp
  game/src/engine/scene/Scene.h
  game/src/engine/scene/SceneDebugService.cpp
  game/src/engine/scene/SceneList.cpp
  game/src/engine/scene/SceneList.h
  game/src/engine/service/Service.cpp
  game/src/engine/service/Service.h
  game/src/engine/service/ServiceProvider.cpp
  game/src/engine/service/ServiceProvider.h
  game/src/game/GameApp.cpp
  game/src/game/GameApp.h
  game/src/game/components/RaycastComponent.cpp
  game/src/game/components/RaycastComponent.h
  game/src/game/components/VehicleComponent.cpp
  game/src/game/components/VehicleComponent.h
  thirdparty/CMakeLists.txt
Labels: framework

#79 Feat/hit-box
  game/src/engine/physics/Hitbox.cpp
  game/src/engine/physics/Hitbox.h
  game/src/game/GameApp.cpp
  game/src/game/components/RaycastComponent.cpp
  game/src/game/components/RaycastComponent.h
  game/src/game/components/VehicleComponent.cpp
  game/src/game/components/VehicleComponent.h
Labels: feature, gameplay, physics
